#################################### Server ####################################
[server]
protocol = http
http_addr = 0.0.0.0
http_port = 3000
domain = localhost
root_url = http://localhost:3001

#################################### Database ####################################
[database]
type = sqlite3
path = ./grafana.db
max_open_conn = 300

#################################### Auth ####################################
[auth]
# Отключить логин форму - использовать Anonymous с правами Admin
disable_login_form = true

[auth.anonymous]
enabled = true
org_role = Admin

#################################### Paths ####################################
[paths]
data = ./data
logs = ./logs

#################################### Session ####################################
[session]
cookie_name = grafana_session
cookie_secure = false
session_life_time = 86400

#################################### Security ####################################
[security]
admin_user = admin
admin_password = admin
secret_key = sw7yqjf0gl1wewf0923f0wads0f

#################################### Logging ####################################
[log]
mode = console file
level = info
